### ISSUE TITLE
Raise errors instead of info logging in certain functions

### ISSUE THREAD

**Issue by lschall** [SiLab-Bonn/lf-monopix2-daq#4]
Several functions e.g. [set_global_voltage](https://github.com/SiLab-Bonn/lf-monopix2-daq/blob/main/monopix2_daq/monopix2.py#L294) log errors on info level instead of raising an error and breaking the script. Especially for functions controlling power domains of the chip it is better to do the latter.

**Comment by idcs0906** [comment]
Solved with PR #6
